import fristImage from './chuancai.jpg';
import secondImage from './lucai.jpg';
import thirdImage from './yuecai.jpg';

const MAIN_DATA = [
    { title:"Sichuan cuisine", content: "Sichuan cuisine or Sichuanese cuisine, alternatively romanized as Szechwan cuisine or Szechuan cuisine, is a style of Chinese cuisine originating from Sichuan province and the neighboring Chongqing municipality. Chongqing was formerly a part of Sichuan until 1997. There are many local variations within Sichuan and Chongqing.It has bold flavours, particularly the pungency and spiciness resulting from liberal use of garlic and chili peppers, as well as the unique flavour of Sichuan pepper. Some examples are Kung Pao chicken and Yuxiang shredded pork. Four sub-styles of Sichuan cuisine include Chongqing, Chengdu, Zigong and Buddhist vegetarian style.", image:fristImage },
    { title:"Shandong cuisine", content: "Shandong cuisine, more commonly known in Chinese as Lu cuisine, is one of the Eight Culinary Traditions of Chinese cuisine and one of the Four Great Traditions. It is derived from the native cooking style of Shandong Province, a northern coastal province of China.Shandong cuisine is famous for its wide selection of material and use of different cooking methods. The raw materials are mainly domestic animals and birds, seafood and vegetables. The masterly cooking techniques include bao, liu, pa, kao, zhu, and coating sugar onto fruits with honey as the adhesive.", image:secondImage },
    { title:"Cantonese cuisine", content: "Cantonese or Guangdong cuisine, also known as Yue cuisine is the cuisine of Guangdong province of China, particularly the provincial capital Guangzhou, and the surrounding regions in the Pearl River Delta including Hong Kong and Macau. Strictly speaking, Cantonese cuisine is the cuisine of Guangzhou or of Cantonese speakers, but it often includes the cooking styles of all the speakers of Yue Chinese languages in Guangdong.The Teochew cuisine and Hakka cuisine of Guangdong are considered their own styles. However, scholars may categorize Guangdong cuisine into three major groups based on the region's dialect: Cantonese, Hakka and Chaozhou cuisines. Neighboring Guangxi's cuisine is also considered separate despite eastern Guangxi being considered culturally Cantonese due to the presence of ethnic Zhuang influences in the rest of the province.", image:thirdImage },
  ];
  
  export { MAIN_DATA };